# HTTP Server配置
[server]
    Env            = "dev"
    GinMode        = "debug"

	Address        = "127.0.0.1:8199"
	ServerRoot     = "public"
	ServerAgent    = "gf-demos"
	NameToUriType  = 2
	RouteOverWrite = true


    LogPath           = "./storage/logs"
    LogStdout         = false
    ErrorStack        = true
    ErrorLogEnabled   = true
    ErrorLogPattern   = "error.{Ymd}.log"
    AccessLogEnabled  = false
    AccessLogPattern  = "access.{Ymd}.log"

# Redis数据库配置
[redis]
        host="127.0.0.1"
        password="null"
        port="6379"
        database=0